# ========================================
# Environment-specific Package Configuration
# ========================================
# Define required packages for different environments

[data.environments.desktop]
packages = ["firefox", "code", "docker"]
services = ["docker", "ssh"]

[data.environments.server]
packages = ["htop", "tmux", "vim"]
services = ["ssh"]

[data.environments.container]
packages = ["curl", "git"]
services = []

[data.os.windows]
packages = [
  "scoop",
  "git",
  "neovim",
  "starship",
  "powershell",
  "fzf",
  "zoxide",
  "eza"
]