# 备用密钥配置
# 当 1Password 不可用或在远程环境时使用

# 1Password 不可用或在远程环境 - 使用默认值
[data.secrets]
  # Git 配置 (默认值)
  git_user_email = "ln1.opensource@gmail.com"
  git_signing_key = ""
  
  # API Keys (空值，需要手动配置)
  openai_api_key = ""
  
  # Google Cloud (空值)
  google_cloud_project = ""
  
  # Aliyun Server (空值)
  aliyun_server_url = ""
  aliyun_server_username = ""

  # MySQL/MariaDB (空值)
  db_user = ""
  db_pass = ""
  db_host = ""
  db_port = ""