  enable_ai_tools = true
  enable_proxy = true
  {{- if or (env "SSH_CONNECTION") (env "SSH_CLIENT") }}
  enable_1password = false  # 远程环境禁用 1Password
  {{- else }}
  enable_1password = true   # 本地环境启用 1Password
  {{- end }}
  enable_oh_my_zsh = false  # 禁用 Oh My Zsh
  enable_zim = true         # 启用 Zim 框架
  {{- if lookPath "starship" }}
  enable_starship = true    # 启用 Starship 提示符
  {{- else }}
  enable_starship = false   # 启用 Starship 提示符 (未安装)
  {{- end }}
  {{- if stat (joinPath .chezmoi.homeDir ".evalcache/evalcache.plugin.zsh") }}
  enable_evalcache = true   # 启用 evalcache 缓存以加速 shell 启动
  {{- else }}
  enable_evalcache = false  # 启用 evalcache 缓存以加速 shell 启动 (未安装)
  {{- end }}
  {{- if stat (joinPath .chezmoi.homeDir ".zim/modules/zsh-defer") }}
  enable_zsh_defer = true   # zsh-defer 延迟加载
  {{- else }}
  enable_zsh_defer = false  # zsh-defer 延迟加载 (未安装)
  {{- end }}