{{- if lookPath "fzf" }}
enable_fzf = true
enable_fzf_new = true
{{- else }}
enable_fzf = false
enable_fzf_new = false
{{- end }}

{{- if or (stat (joinPath (env "HOMEBREW_PREFIX" | default "/opt/homebrew") "share/forgit/forgit.plugin.zsh")) (stat (joinPath .chezmoi.homeDir ".forgit/forgit.plugin.zsh")) }}
enable_forgit = true
{{- else }}
enable_forgit = false
{{- end }}

{{- if lookPath "fd" }}
enable_fd = true
{{- else }}
enable_fd = false
{{- end }}

{{- if lookPath "eza" }}
enable_eza = true
{{- else }}
enable_eza = false
{{- end }}

{{- if lookPath "exa" }}
enable_exa = true
{{- else }}
enable_exa = false
{{- end }}

{{- if lookPath "zoxide" }}
enable_zoxide = true
{{- else }}
enable_zoxide = false
{{- end }}

{{- if lookPath "atool" }}
enable_atool = true
{{- else }}
enable_atool = false
{{- end }}

{{- if lookPath "bat" }}
enable_bat = true
{{- else }}
enable_bat = false
{{- end }}

# Development environment management (based on actual installation)
{{- if lookPath "git" }}
enable_git = true
{{- else }}
enable_git = false
{{- end }}

{{- if lookPath "pyenv" }}
enable_pyenv = true
{{- else }}
enable_pyenv = false
{{- end }}

{{- if lookPath "rbenv" }}
enable_rbenv = true
{{- else }}
enable_rbenv = false
{{- end }}

{{- if lookPath "fnm" }}
enable_fnm = true
{{- else }}
enable_fnm = false
{{- end }}

{{- if lookPath "mise" }}
enable_mise = true
{{- else }}
enable_mise = false
{{- end }}

{{- if or (lookPath "conda") (stat (joinPath .chezmoi.homeDir "miniconda3")) (stat (joinPath .chezmoi.homeDir "anaconda3")) }}
enable_conda = true
{{- else }}
enable_conda = false
{{- end }}

# Programming language support
enable_node = true
enable_python = true
enable_go = false
enable_rust = false

# Container and virtualization (based on actual installation)
{{- if lookPath "docker" }}
enable_docker = true
{{- else }}
enable_docker = false
{{- end }}

{{- if lookPath "kubectl" }}
enable_kubectl = true
{{- else }}
enable_kubectl = false
{{- end }}

# System tools (based on actual installation)
{{- if lookPath "ssh" }}
enable_ssh = true
{{- else }}
enable_ssh = false
{{- end }}

{{- if lookPath "curl" }}
enable_curl = true
{{- else }}
enable_curl = false
{{- end }}

{{- if lookPath "wget" }}
enable_wget = true
{{- else }}
enable_wget = false
{{- end }}

# Editor tools (based on actual installation)
{{- if lookPath "code" }}
enable_vscode = true
{{- else }}
enable_vscode = false
{{- end }}

{{- if lookPath "vim" }}
enable_vim = true
{{- else }}
enable_vim = false
{{- end }}

{{- if lookPath "nvim" }}
enable_nvim = true
{{- else }}
enable_nvim = false
{{- end }}

{{- if lookPath "nano" }}
enable_nano = true
{{- else }}
enable_nano = false
{{- end }}

{{- if lookPath "vi" }}
enable_vi = true
{{- else }}
enable_vi = false
{{- end }}

# System monitoring tools (based on actual installation)
{{- if lookPath "htop" }}
enable_htop = true
{{- else }}
enable_htop = false
{{- end }}

{{- if lookPath "top" }}
enable_top = true
{{- else }}
enable_top = false
{{- end }}

{{- if lookPath "free" }}
enable_free = true
{{- else }}
enable_free = false
{{- end }}

{{- if lookPath "ps" }}
enable_ps = true
{{- else }}
enable_ps = false
{{- end }}

{{- if lookPath "netstat" }}
enable_netstat = true
{{- else }}
enable_netstat = false
{{- end }}

{{- if lookPath "ss" }}
enable_ss = true
{{- else }}
enable_ss = false
{{- end }}

# Development environment tools (based on actual installation)
{{- if lookPath "python3" }}
enable_python3 = true
{{- else }}
enable_python3 = false
{{- end }}

{{- if lookPath "python" }}
enable_python2 = true
{{- else }}
enable_python2 = false
{{- end }}

{{- if lookPath "tmux" }}
enable_tmux = true
{{- else }}
enable_tmux = false
{{- end }}

{{- if lookPath "grep" }}
enable_grep = true
{{- else }}
enable_grep = false
{{- end }}

{{- if lookPath "awk" }}
enable_awk = true
{{- else }}
enable_awk = false
{{- end }}

{{- if lookPath "thefuck" }}
enable_fuck = true
{{- else }}
enable_fuck = false
{{- end }}