# Proxy config detection template
# Separate complex proxy detection logic from main config

{{- $http_proxy := env "http_proxy" | default (env "HTTP_PROXY") }}
{{- $https_proxy := env "https_proxy" | default (env "HTTPS_PROXY") }}
{{- $socks_proxy := env "socks_proxy" | default (env "SOCKS_PROXY") }}

{{- if or (and $http_proxy (ne $http_proxy "")) (and $https_proxy (ne $https_proxy "")) (and $socks_proxy (ne $socks_proxy "")) }}
# Use proxy config from environment variables
enabled = true
source = "environment"
http_proxy = "{{ $http_proxy | default "" }}"
https_proxy = "{{ $https_proxy | default "" }}"
socks_proxy = "{{ $socks_proxy | default "" }}"
{{- else }}
{{ includeTemplate "config/proxy/proxy-clash-detection.toml" . }}
{{- end }}