# Disabled proxy config
# Used for environments without proxy support or configuration

# No proxy config found - provide default empty values
enabled = false
http_proxy = ""
https_proxy = ""
socks_proxy = ""