# Clash proxy config detection
# Handle Clash config file detection and port parsing

{{- if or (eq .chezmoi.os "linux") (eq .chezmoi.os "windows") }}
  {{- if or (env "SSH_CONNECTION") (env "SSH_CLIENT") (env "SSH_TTY") }}
    # Remote environment: check subscription.yaml first, fallback to config.yaml
    {{- $subscription_config := joinPath .chezmoi.homeDir ".config/clash/subscription.yaml" }}
    {{- $clash_config := joinPath .chezmoi.homeDir ".config/clash/config.yaml" }}
    {{- if stat $subscription_config }}
      {{- $clash := include $subscription_config | fromYaml }}
{{ includeTemplate "config/proxy/proxy-clash-config.toml" (dict "clash" $clash "config_type" "subscription" "config_file" "subscription.yaml") }}
    {{- else if stat $clash_config }}
      {{- $clash := include $clash_config | fromYaml }}
{{ includeTemplate "config/proxy/proxy-clash-config.toml" (dict "clash" $clash "config_type" "clash" "config_file" "config.yaml") }}
    {{- else }}
{{ includeTemplate "config/proxy/proxy-default.toml" . }}
    {{- end }}
  {{- else }}
    # Desktop environment: keep existing logic
    {{- $clash_config := joinPath .chezmoi.homeDir ".config/clash/config.yaml" }}
    {{- if stat $clash_config }}
      {{- $clash := include $clash_config | fromYaml }}
{{ includeTemplate "config/proxy/proxy-clash-config.toml" (dict "clash" $clash "config_type" "clash" "config_file" "config.yaml") }}
    {{- else }}
{{ includeTemplate "config/proxy/proxy-disabled.toml" . }}
    {{- end }}
  {{- end }}
{{- else }}
{{ includeTemplate "config/proxy/proxy-disabled.toml" . }}
{{- end }}