# ========================================
# Default Proxy Configuration
# ========================================
# Fallback for remote environment when no proxy config file is found

enabled = false
source = "default"
config_file = "subscription.yaml"
log_file = "clash.log"
host = "127.0.0.1"
http_port = 7890
socks_port = 7891
http_proxy = "http://127.0.0.1:7890"
https_proxy = "http://127.0.0.1:7890"
socks_proxy = "socks5://127.0.0.1:7891"