# ========================================
# Disabled Proxy Configuration
# ========================================
# Used for environments without proxy support or configuration
enabled = false
http_proxy = ""
https_proxy = ""
socks_proxy = ""