# Fallback secret config
# Used when 1Password is unavailable or in remote environments

[data.secrets]
# Git config (default value)
git_user_email = "ln1.opensource@gmail.com"
git_signing_key = ""

# API Keys (empty, needs manual config)
openai_api_key = ""

# Google Cloud (empty)
google_cloud_project = ""

# Aliyun Server (empty)
aliyun_server_url = ""
aliyun_server_username = ""

# MySQL/MariaDB (empty)
db_user = ""
db_pass = ""
db_host = ""
db_port = ""