# 1Password secret config
# Key reading config when 1Password is available

[onepassword]
prompt = false
cache = true

# Unified secret reading - all 1Password calls here
[data.secrets]
# Git config
git_user_email = "{{ onepasswordRead "op://Work/Git Signing Key/email" }}"
git_signing_key = "{{ onepasswordRead "op://Work/Git Signing Key/public key" }}"

# API Keys
openai_api_key = "{{ onepasswordRead "op://Work/OpenAI-API-Key/api-key" }}"

# Google Cloud
google_cloud_project = "{{ onepasswordRead "op://Work/Google Cloud/Project ID" }}"

# Aliyun Server 
aliyun_server_url = "{{ onepasswordRead "op://Work/Aliyun/URL" }}"
aliyun_server_username = "{{ onepasswordRead "op://Work/Aliyun/username" }}"

# MySQL/MariaDB
db_user = "{{ onepasswordRead "op://Work/Ali-MySQL/username" }}"
db_pass = "{{ onepasswordRead "op://Work/Ali-MySQL/password" }}"
db_host = "{{ onepasswordRead "op://Work/Ali-MySQL/server" }}"
db_port = "{{ onepasswordRead "op://Work/Ali-MySQL/port" }}"