# ========================================
# Fallback Secrets Configuration
# ========================================
# Used when 1Password is unavailable or in remote environments

[data.secrets]
# Git Configuration
git_user_email = "ln1.opensource@gmail.com"
git_signing_key = ""

# API Keys
openai_api_key = ""

# Google Cloud
google_cloud_project = ""

# Aliyun Server
aliyun_server_url = ""
aliyun_server_username = ""

# MySQL/MariaDB (empty)
db_user = ""
db_pass = ""
db_host = ""
db_port = ""